<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>How to catch and print the full exception traceback without halting/exiting the program? | StackOverflow Snapshot</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="canonical" href="https://ohstackoverflow.netlify.app/posts/how-to-catch-and-print-the-full-exception-traceback-without-halting-exiting-the-program/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Arya">
<link rel="prev" href="../how-does-the-property-decorator-work-in-python/" title="How does the @property decorator work in Python?" type="text/html">
<link rel="next" href="../what-does-the-b-character-do-in-front-of-a-string-literal/" title="What does the 'b' character do in front of a string literal?" type="text/html">
<meta property="og:site_name" content="StackOverflow Snapshot">
<meta property="og:title" content="How to catch and print the full exception traceback without halting/ex">
<meta property="og:url" content="https://ohstackoverflow.netlify.app/posts/how-to-catch-and-print-the-full-exception-traceback-without-halting-exiting-the-program/">
<meta property="og:description" content="I want to catch and log exceptions without exiting, e.g.,
try:
    do_stuff()
except Exception as err:
    print(Exception, err)
    # I want to print the entire traceback here,
    # not just the exc">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2023-02-17T03:35:51+08:00">
<meta property="article:tag" content="exception">
<meta property="article:tag" content="python">
<meta property="article:tag" content="traceback">
<meta property="article:tag" content="try-catch">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Menubar -->

<nav class="navbar navbar-inverse navbar-static-top"><div class="container">
<!-- This keeps the margins nice -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="https://ohstackoverflow.netlify.app/">

                <span id="blog-title">StackOverflow Snapshot</span>
            </a>
        </div>
<!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="bs-navbar" aria-expanded="false">
            <ul class="nav navbar-nav">
<li>
<a href="../../archive.html">Archive</a>
                </li>
<li>
<a href="../../categories/">Tags</a>

                
            </li>
</ul>
<ul class="nav navbar-nav navbar-right">
<div style="display:table;min-height:5rem;min-width:27rem;">
					<div class="input-group" style="display: table-cell;vertical-align: middle;">
						<input id="words" type="text" class="form-control" style="max-width:22rem;" onkeydown="if(event.keyCode==13){btn.click()}"><span class="input-group-btn" style="float:left">
							<button id="btn" class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">
								<span class="glyphicon glyphicon-search">
							</span></button>
						</span>
					</div>
<!-- /input-group -->
				</div>

				
                
                
                
            </ul>
</div>
<!-- /.navbar-collapse -->
    </div>
<!-- /.container -->
</nav><!-- End of Menubar --><!-- 模态框（Modal） --><div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×
				</button>
				<h4 class="modal-title" id="myModalLabel">
					查找结果
				</h4>
			</div>
			<div class="modal-body">
				<div id="search-count" style="min-height:4rem;">
				查找中，请稍后...
				</div>
				<div id="search-result">
				</div>

				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">
					关闭
				</button>
			</div>
		</div>
<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        <div class="row">
            
            
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">How to catch and print the full exception traceback without halting/exiting the program?</a></h1>

        <div class="metadata">
            <p class="byline author vcard p-author h-card"><span class="byline-name fn p-name" itemprop="author">
                    <a class="u-url" href="../../authors/arya/">Arya</a>
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2023-02-17T03:35:51+08:00" itemprop="datePublished" title="2023-02-17 03:35">2023-02-17 03:35</time></a>
            </p>
            

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <p>I want to catch and log exceptions without exiting, e.g.,</p>
<div class="code"><pre class="code literal-block"><span class="k">try</span><span class="o">:</span>
<span class="w">    </span><span class="n">do_stuff</span><span class="o">()</span>
<span class="n">except</span><span class="w"> </span><span class="n">Exception</span><span class="w"> </span><span class="k">as</span><span class="w"> </span><span class="n">err</span><span class="o">:</span>
<span class="w">    </span><span class="n">print</span><span class="o">(</span><span class="n">Exception</span><span class="o">,</span><span class="w"> </span><span class="n">err</span><span class="o">)</span>
<span class="w">    </span><span class="err">#</span><span class="w"> </span><span class="n">I</span><span class="w"> </span><span class="n">want</span><span class="w"> </span><span class="n">to</span><span class="w"> </span><span class="n">print</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">entire</span><span class="w"> </span><span class="n">traceback</span><span class="w"> </span><span class="n">here</span><span class="o">,</span>
<span class="w">    </span><span class="err">#</span><span class="w"> </span><span class="n">not</span><span class="w"> </span><span class="n">just</span><span class="w"> </span><span class="n">the</span><span class="w"> </span><span class="n">exception</span><span class="w"> </span><span class="n">name</span><span class="w"> </span><span class="n">and</span><span class="w"> </span><span class="n">details</span>
</pre></div>

<p>I want to print the exact same output that is printed when the exception is
raised without the try/except intercepting the exception, and I do <em>not</em> want
it to exit my program.</p>
<p><br><br></p>
<h2>Answer</h2>
<p>Some other answer have already pointed out the traceback module.</p>
<p>Please notice that with <code>print_exc</code>, in some corner cases, you will not obtain
what you would expect. In Python 2.x:</p>
<div class="code"><pre class="code literal-block"><span class="kn">import</span> <span class="nn">traceback</span>

<span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Oups!"</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Again !?!"</span><span class="p">)</span>
    <span class="k">except</span><span class="p">:</span>
        <span class="k">pass</span>

    <span class="n">traceback</span><span class="o">.</span><span class="n">print_exc</span><span class="p">()</span>
</pre></div>

<p>...will display the traceback of the <em>last</em> exception:</p>
<div class="code"><pre class="code literal-block">Traceback (most recent call last):
  File "e.py", line 7, in &lt;module&gt;
    raise TypeError("Again !?!")
TypeError: Again !?!
</pre></div>

<p><strong>If you really need to access the original <em>traceback</em></strong> one solution is to
cache the <em>exception infos</em> as returned from <code>exc_info</code> in a local variable
and display it using <code>print_exception</code>:</p>
<div class="code"><pre class="code literal-block"><span class="kn">import</span> <span class="nn">traceback</span>
<span class="kn">import</span> <span class="nn">sys</span>

<span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Oups!"</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">exc_info</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()</span>

        <span class="c1"># do you usefull stuff here</span>
        <span class="c1"># (potentially raising an exception)</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Again !?!"</span><span class="p">)</span>
        <span class="k">except</span><span class="p">:</span>
            <span class="k">pass</span>
        <span class="c1"># end of useful stuff</span>


    <span class="k">finally</span><span class="p">:</span>
        <span class="c1"># Display the *original* exception</span>
        <span class="n">traceback</span><span class="o">.</span><span class="n">print_exception</span><span class="p">(</span><span class="o">*</span><span class="n">exc_info</span><span class="p">)</span>
        <span class="k">del</span> <span class="n">exc_info</span>
</pre></div>

<p>Producing:</p>
<div class="code"><pre class="code literal-block">Traceback (most recent call last):
  File "t.py", line 6, in &lt;module&gt;
    raise TypeError("Oups!")
TypeError: Oups!
</pre></div>

<p>Few pitfalls with this though:</p>
<ul>
<li>From the doc of <code>sys_info</code>:</li>
</ul>
<blockquote>
<p>Assigning the traceback return value to a local variable in a function that
is handling an exception will cause a <strong>circular reference</strong>. This will
prevent anything referenced by a local variable in the same function or by
the traceback from being garbage collected. [...] <strong>If you do need the
traceback, make sure to delete it after use</strong> (best done with a try ...
finally statement)</p>
</blockquote>
<ul>
<li>but, from the same doc:</li>
</ul>
<blockquote>
<p><strong>Beginning with Python 2.2, such cycles are automatically reclaimed</strong> when
garbage collection is enabled and they become unreachable, but it remains
more efficient to avoid creating cycles.</p>
</blockquote>
<hr>
<p>On the other hand, by allowing you to access the traceback <em>associated with</em>
an exception, Python 3 produce a less surprising result:</p>
<div class="code"><pre class="code literal-block"><span class="kn">import</span> <span class="nn">traceback</span>

<span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Oups!"</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Again !?!"</span><span class="p">)</span>
    <span class="k">except</span><span class="p">:</span>
        <span class="k">pass</span>

    <span class="n">traceback</span><span class="o">.</span><span class="n">print_tb</span><span class="p">(</span><span class="n">err</span><span class="o">.</span><span class="n">__traceback__</span><span class="p">)</span>
</pre></div>

<p>... will display:</p>
<div class="code"><pre class="code literal-block">  File "e3.py", line 4, in &lt;module&gt;
    raise TypeError("Oups!")
</pre></div>

<p><br></p>
<h3>Suggest</h3>
<p>Some other answer have already pointed out the traceback module.</p>
<p>Please notice that with <code>print_exc</code>, in some corner cases, you will not obtain
what you would expect. In Python 2.x:</p>
<div class="code"><pre class="code literal-block"><span class="kn">import</span> <span class="nn">traceback</span>

<span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Oups!"</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Again !?!"</span><span class="p">)</span>
    <span class="k">except</span><span class="p">:</span>
        <span class="k">pass</span>

    <span class="n">traceback</span><span class="o">.</span><span class="n">print_exc</span><span class="p">()</span>
</pre></div>

<p>...will display the traceback of the <em>last</em> exception:</p>
<div class="code"><pre class="code literal-block">Traceback (most recent call last):
  File "e.py", line 7, in &lt;module&gt;
    raise TypeError("Again !?!")
TypeError: Again !?!
</pre></div>

<p><strong>If you really need to access the original <em>traceback</em></strong> one solution is to
cache the <em>exception infos</em> as returned from <code>exc_info</code> in a local variable
and display it using <code>print_exception</code>:</p>
<div class="code"><pre class="code literal-block"><span class="kn">import</span> <span class="nn">traceback</span>
<span class="kn">import</span> <span class="nn">sys</span>

<span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Oups!"</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span><span class="p">,</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">exc_info</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()</span>

        <span class="c1"># do you usefull stuff here</span>
        <span class="c1"># (potentially raising an exception)</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Again !?!"</span><span class="p">)</span>
        <span class="k">except</span><span class="p">:</span>
            <span class="k">pass</span>
        <span class="c1"># end of useful stuff</span>


    <span class="k">finally</span><span class="p">:</span>
        <span class="c1"># Display the *original* exception</span>
        <span class="n">traceback</span><span class="o">.</span><span class="n">print_exception</span><span class="p">(</span><span class="o">*</span><span class="n">exc_info</span><span class="p">)</span>
        <span class="k">del</span> <span class="n">exc_info</span>
</pre></div>

<p>Producing:</p>
<div class="code"><pre class="code literal-block">Traceback (most recent call last):
  File "t.py", line 6, in &lt;module&gt;
    raise TypeError("Oups!")
TypeError: Oups!
</pre></div>

<p>Few pitfalls with this though:</p>
<ul>
<li>From the doc of <code>sys_info</code>:</li>
</ul>
<blockquote>
<p>Assigning the traceback return value to a local variable in a function that
is handling an exception will cause a <strong>circular reference</strong>. This will
prevent anything referenced by a local variable in the same function or by
the traceback from being garbage collected. [...] <strong>If you do need the
traceback, make sure to delete it after use</strong> (best done with a try ...
finally statement)</p>
</blockquote>
<ul>
<li>but, from the same doc:</li>
</ul>
<blockquote>
<p><strong>Beginning with Python 2.2, such cycles are automatically reclaimed</strong> when
garbage collection is enabled and they become unreachable, but it remains
more efficient to avoid creating cycles.</p>
</blockquote>
<hr>
<p>On the other hand, by allowing you to access the traceback <em>associated with</em>
an exception, Python 3 produce a less surprising result:</p>
<div class="code"><pre class="code literal-block"><span class="kn">import</span> <span class="nn">traceback</span>

<span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Oups!"</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">err</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">TypeError</span><span class="p">(</span><span class="s2">"Again !?!"</span><span class="p">)</span>
    <span class="k">except</span><span class="p">:</span>
        <span class="k">pass</span>

    <span class="n">traceback</span><span class="o">.</span><span class="n">print_tb</span><span class="p">(</span><span class="n">err</span><span class="o">.</span><span class="n">__traceback__</span><span class="p">)</span>
</pre></div>

<p>... will display:</p>
<div class="code"><pre class="code literal-block">  File "e3.py", line 4, in &lt;module&gt;
    raise TypeError("Oups!")
</pre></div>
    </div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/exception/" rel="tag">exception</a></li>
            <li><a class="tag p-category" href="../../categories/python/" rel="tag">python</a></li>
            <li><a class="tag p-category" href="../../categories/traceback/" rel="tag">traceback</a></li>
            <li><a class="tag p-category" href="../../categories/try-catch/" rel="tag">try-catch</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../how-does-the-property-decorator-work-in-python/" rel="prev" title="How does the @property decorator work in Python?">Previous post</a>
            </li>
            <li class="next">
                <a href="../what-does-the-b-character-do-in-front-of-a-string-literal/" rel="next" title="What does the 'b' character do in front of a string literal?">Next post</a>
            </li>
        </ul></nav></aside></article>
</div>
        <!--End of body content-->

        <footer id="footer">
            Contents © 2023         Go to StackOverflow Chinese Site  <a href="http://stackoverflow.ink">StackOverflow中文网</a>  
            
        </footer>
</div>
</div>


            <script src="../../assets/js/all-nocdn.js"></script><!-- fancy dates --><script>
    moment.locale("en");
    fancydates(0, "YYYY-MM-DD HH:mm");
    </script><!-- end fancy dates --><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element) {
            return element.getElementsByTagName('img')[0].alt;
    }});
    </script><script src="../../assets/js/search.js"></script>
</body>
</html>
